# Generated by Django 4.2.7 on 2025-12-06 14:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('rentals', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_timestamp', models.DateTimeField(auto_now_add=True, help_text='When the return was processed')),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount refunded to customer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fee charged (for rental returns)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason', models.TextField(blank=True, help_text='Reason for return')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Employee who processed the return', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='employees.employee')),
                ('original_rental', models.ForeignKey(blank=True, help_text='Original rental (if returning from rental)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='rentals.rental')),
                ('original_sale', models.ForeignKey(blank=True, help_text='Original sale (if returning from sale)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'db_table': 'returns',
                'ordering': ['-return_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity returned', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (from original transaction)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total refund for this line', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.item')),
                ('return_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'db_table': 'return_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['-return_timestamp'], name='returns_return__fb8a84_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['employee'], name='returns_employe_ff624d_idx'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(check=models.Q(('original_sale__isnull', False), ('original_rental__isnull', False), _connector='OR'), name='return_must_have_original'),
        ),
    ]
