# Generated by Django 4.2.7 on 2025-12-06 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Unique username for login', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(help_text='Full name of employee', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('position', models.CharField(choices=[('Admin', 'Admin'), ('Cashier', 'Cashier')], help_text='Employee role: Admin or Cashier', max_length=20)),
                ('password_hash', models.CharField(help_text='Hashed password (never store plain text!)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When employee was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When employee was last updated')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('SALE', 'Sale Transaction'), ('RENTAL', 'Rental Transaction'), ('RETURN', 'Return Transaction'), ('EMPLOYEE_CREATE', 'Employee Created'), ('EMPLOYEE_UPDATE', 'Employee Updated'), ('EMPLOYEE_DELETE', 'Employee Deleted'), ('INVENTORY_UPDATE', 'Inventory Updated')], max_length=50)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Activity Log',
                'verbose_name_plural': 'Employee Activity Logs',
                'db_table': 'employee_activity_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='employee_ac_timesta_3e1378_idx'), models.Index(fields=['employee', '-timestamp'], name='employee_ac_employe_38b0cd_idx'), models.Index(fields=['action'], name='employee_ac_action_feb13b_idx')],
            },
        ),
    ]
