# Generated by Django 4.2.7 on 2025-12-06 14:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(help_text='Customer phone number (10 digits)', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('rental_timestamp', models.DateTimeField(auto_now_add=True, help_text='When the rental was made')),
                ('due_date', models.DateTimeField(help_text='When items should be returned')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total rental cost', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Employee who processed the rental', on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'db_table': 'rentals',
                'ordering': ['-rental_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity rented', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Rental price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_items', to='inventory.item')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Rental Item',
                'verbose_name_plural': 'Rental Items',
                'db_table': 'rental_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['-rental_timestamp'], name='rentals_rental__868a73_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['customer_phone'], name='rentals_custome_e385fd_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status'], name='rentals_status_443aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['due_date'], name='rentals_due_dat_f32c15_idx'),
        ),
    ]
